export const WORDS: string[] = [
  'Three-pointer',
  'Slam dunk',
  'Fast break',
  'Pick and roll',
  'Alley-oop',
  'Buzzer beater',
  'Triple-double',
  'Double-double',
  'Steal',
  'Block',
  'Rebound',
  'LeBron James',
  'Stephen Curry',
  'Kevin Durant',
  'Michael Jordan',
  'Kobe Bryant',
  'Shaquille O\'Neal',
  'NBA Finals',
  'MVP',
  'All-Star',
  'Draft',
  'Trade deadline',
  'Salary cap',
  'Point guard',
  'Shooting guard',
  'Power forward',
  'Center',
  'Zone defense',
  'Full-court press',
  'Overtime',
  'Technical foul',
  'Flagrant foul',
  'Free throw',
  'Possession',
  'Turnover',
  'And-one',
  'Crossover',
  'Spin move',
  'Euro step',
  'Poster dunk',
  'Rim protector',
  'Bench mob',
  'Sixth man',
  'Playoff push',
  'Championship ring',
]
