export const WORDS: string[] = [
  'Goal',
  'Penalty',
  'Free kick',
  'Corner',
  'Offside',
  'VAR',
  'Yellow card',
  'Red card',
  'Nil-nil',
  'Hat-trick',
  'Clean sheet',
  'Goalkeeper',
  'Striker',
  'Midfielder',
  'Defender',
  'Counter-attack',
  'High press',
  'Gegenpressing',
  'Messi',
  'Ronaldo',
  'Mbappé',
  'Haaland',
  'World Cup',
  'Champions League',
  'Premier League',
  'La Liga',
  'Bundesliga',
  'Serie A',
  'Transfer window',
  'Deadline day',
  'Injury time',
  'Extra time',
  'Penalty shootout',
  'Dribble',
  'Assist',
  'Brace',
  'Man of the match',
  'Relegated',
  'Title race',
  'Derby',
  'Fan chant',
  'Stadium atmosphere',
  'Own goal',
  'Bicycle kick',
  'Volley',
]
