export const WORDS: string[] = [
  'Luke Skywalker',
  'Princess Leia',
  'Han Solo',
  'Obi-Wan Kenobi',
  'Darth Vader',
  'Grand Moff Tarkin',
  'R2-D2',
  'C-3PO',
  'Chewbacca',
  'Jabba the Hutt',
  'Greedo',
  'Tatooine',
  'Mos Eisley',
  'Death Star',
  'Alderaan',
  'Binary sunset',
  'Uncle Owen',
  'Aunt Beru',
  'Tusken Raiders',
  'Cantina band',
  'Stormtrooper armor',
  'Lightsaber',
  'Millennium Falcon',
  'X-wing',
  'TIE fighter',
  'Proton torpedoes',
  'Tractor beam',
  'Trash compactor',
  'Help me Obi-Wan',
  'Use the Force',
  'I have a bad feeling about this',
  'These aren\'t the droids you\'re looking for',
  'May the Force be with you',
  'Blast! This is all your fault',
  'Aren\'t you a little short for a stormtrooper',
  'Chewie, get us out of here',
  'Red Five',
  'Yavin 4',
  'Exhaust port',
  'One in a million shot',
]
