export const WORDS: string[] = [
  'Anakin Skywalker',
  'Padmé Amidala',
  'Obi-Wan Kenobi',
  'Count Dooku',
  'Jango Fett',
  'young Boba Fett',
  'Mace Windu',
  'Yoda',
  'Coruscant',
  'Geonosis',
  'Kamino',
  'Naboo',
  'Clone army',
  'Geonosian arena',
  'Dooku\'s curved lightsaber',
  'Dexter Jettster',
  'Zam Wesell',
  'Tusken Raiders',
  'I don\'t like sand',
  'I killed them all',
  'Begun the Clone War has',
  'This is a crisis',
  'Anakin\'s feelings for Padmé',
  'Secret wedding',
  'LAAT gunships',
  'Jedi council chamber',
  'Kamino cloners',
  'Lama Su',
  'Prime Minister on Kamino',
  'Bounty hunter chase',
  'Slave I',
  'Seismic charges',
  'Arena beasts',
  'Super battle droids',
  'Republic gunships',
  'Blue hologram meetings',
  'Padmé in chains',
  'Yoda with a lightsaber',
  'Clone troopers marching',
  'War officially starts',
]
