export const WORDS: string[] = [
  'Luke Skywalker',
  'Darth Vader',
  'Yoda',
  'Princess Leia',
  'Han Solo',
  'Lando Calrissian',
  'Boba Fett',
  'Emperor hologram',
  'Wampa',
  'Hoth',
  'Dagobah',
  'Cloud City',
  'Bespin',
  'Asteroid field',
  'AT-AT walker',
  'Snowspeeder',
  'Bacta tank',
  'Carbon freeze',
  'Echo Base',
  'Tauntaun',
  'Probe droid',
  'The Force is strong with this one',
  'Impressive, most impressive',
  'Never tell me the odds',
  'Do or do not, there is no try',
  'No, I am your father',
  'I am your father',
  'Luminous beings are we',
  'Yoda backpack',
  'Training with rocks',
  'Cave vision',
  'Han in carbonite',
  'Bounty hunters',
  'Imperial March',
  'Executor',
  'Millennium Falcon repairs',
  'Leia and Han kiss',
  'My hands are dirty too',
  'Disappearing in the mist',
  'City in the clouds',
]
