export const WORDS: string[] = [
  'Rey',
  'Finn',
  'Poe Dameron',
  'Kylo Ren',
  'Han Solo',
  'Leia Organa',
  'BB-8',
  'Supreme Leader Snoke',
  'Captain Phasma',
  'Maz Kanata',
  'Jakku',
  'Starkiller Base',
  'Takodana',
  'D\'Qar',
  'First Order',
  'The Resistance',
  'Chewie, we\'re home',
  'That\'s not how the Force works',
  'I will finish what you started',
  'The Force, it\'s calling to you',
  'Traitor!',
  'Scavenger staff',
  'Niima Outpost',
  'Map to Luke',
  'Millennium Falcon escape',
  'TR-8R',
  'Crossguard lightsaber',
  'Forest duel in the snow',
  'Han and Chewie return',
  'Maz\'s castle',
  'Rathtars',
  'FN-2187',
  'Sanitation joke',
  'Jedi mind pull',
  'Luke on the cliff',
  'X-wing assault',
  'Star Destroyer graveyard',
  'Snoke hologram',
  'Kylo tantrum',
  'A new generation',
]
