export const WORDS: string[] = [
  'Rey',
  'Luke Skywalker',
  'Kylo Ren',
  'General Hux',
  'Rose Tico',
  'DJ',
  'Vice Admiral Holdo',
  'Snoke',
  'Ahch-To',
  'Crait',
  'Canto Bight',
  'Supremacy flagship',
  'Let the past die',
  'This is not going to go the way you think',
  'Impressive',
  'The Jedi must end',
  'Holdo maneuver',
  'Roses not porgs',
  'I only know one truth',
  'Porgs',
  'Blue milk',
  'Projection on Crait',
  'Red salt',
  'Praetorian Guards',
  'Throne room team-up',
  'Codebreaker',
  'Master Codebreaker',
  'Fathiers',
  'Broom boy',
  'Resistance bombers',
  'Dreadnought attack',
  'Mirror cave',
  'Force bond',
  'Spark that lights the fire',
  'We are the spark',
  'Luke brushing the shoulder',
  'No one\'s ever really gone',
  'Old Jedi texts',
  'Green milk',
  'Legend of Luke',
]
