export const WORDS: string[] = [
  'Qui-Gon Jinn',
  'young Obi-Wan',
  'young Anakin',
  'Padmé Amidala',
  'Darth Maul',
  'Senator Palpatine',
  'Jar Jar Binks',
  'Boss Nass',
  'Watto',
  'Sebulba',
  'Naboo',
  'Coruscant',
  'Tatooine',
  'Gungan City',
  'Double-bladed lightsaber',
  'Podracer',
  'Trade Federation ship',
  'Battle droids',
  'Queen Amidala decoy',
  'Duel of the Fates',
  'Theed palace',
  'Naboo starfighter',
  'Midi-chlorians',
  'There\'s always a bigger fish',
  'Are you an angel?',
  'I will be the most powerful Jedi ever',
  'The ability to speak does not make you intelligent',
  'Yippee!',
  'Meesa Jar Jar Binks',
  'Boonta Eve Classic',
  'Pit droids',
  'Mos Espa',
  'Sith reveal',
  'Darth Sidious hologram',
  'Qui-Gon\'s funeral',
  'Senate vote of no confidence',
  'Gungan army',
  'Destroyer droids',
  'Anakin\'s podracer engines',
  'Balance of the Force',
]
