export const WORDS: string[] = [
  'Luke Skywalker',
  'Darth Vader',
  'Emperor Palpatine',
  'Jabba the Hutt',
  'Lando Calrissian',
  'Ewoks',
  'Boba Fett',
  'Admiral Ackbar',
  'Mon Mothma',
  'Jabba\'s palace',
  'Tatooine',
  'Endor',
  'Death Star II',
  'Sarlacc pit',
  'Endor bunker',
  'Speeder bike chase',
  'Green lightsaber',
  'Sail barge',
  'Rancor pit',
  'Bib Fortuna',
  'Max Rebo Band',
  'It\'s a trap!',
  'Return of the Jedi',
  'Come to the dark side',
  'Your father he is',
  'The Emperor is not as forgiving as I am',
  'So be it, Jedi',
  'Shield generator',
  'Golden bikini',
  'Forest moon',
  'I am a Jedi, like my father before me',
  'Blue milk callback',
  'Wicket',
  'Emperor throne room',
  'Force lightning',
  'Funeral pyre',
  'Victory celebration',
  'Nien Nunb',
  'Many Bothans died',
  'Redemption arc',
]
