export const WORDS: string[] = [
  'Anakin Skywalker',
  'Obi-Wan Kenobi',
  'Palpatine',
  'Darth Sidious',
  'General Grievous',
  'Padmé Amidala',
  'Yoda',
  'Mace Windu',
  'Order 66',
  'Mustafar',
  'Coruscant',
  'Utapau',
  'I have the high ground',
  'You were the chosen one!',
  'Execute Order 66',
  'So this is how liberty dies',
  'Darth... Vader',
  'Hello there',
  'It\'s over Anakin',
  'Battle over Coruscant',
  'Invisible Hand',
  'Count Dooku execution',
  'Buzz droids',
  'Grievous cough',
  'Utapau sinkhole',
  'Younglings',
  'Temple march',
  'Padmé\'s funeral',
  'Blue lightsaber duel',
  'Mustafar lava river',
  'Vader suit assembly',
  'Birth of Luke and Leia',
  'Bail Organa',
  'Operation Knightfall',
  'Tragedy of Darth Plagueis',
  'Unlimited power',
  'Mace out the window',
  'Yoda vs Sidious',
  'Not from a Jedi',
  'Twins separated',
]
