export const WORDS: string[] = [
  'Rey',
  'Kylo Ren',
  'Ben Solo',
  'Emperor Palpatine',
  'Zorii Bliss',
  'Jannah',
  'Babu Frik',
  'Leia Organa',
  'Exegol',
  'Kijimi',
  'Death Star ruins',
  'Somehow Palpatine returned',
  'I am all the Jedi',
  'Rey Skywalker',
  'The Rise of Skywalker',
  'Dyad in the Force',
  'Ochi',
  'Wayfinder',
  'Sith dagger',
  'Dark Rey',
  'Festival of the Ancestors',
  'Pasaana',
  'Red stormtroopers',
  'Knights of Ren',
  'Chewie fake-out',
  'Force healing',
  'Be with me',
  'Han memory scene',
  'Yellow lightsaber',
  'Ben Solo shrug',
  'Exegol fleet',
  'Final Order',
  'Lando returns',
  'Leia training flashback',
  'Babu Frik workshop',
  'Kijimi spice runner',
  'Jannah on the moon',
  'Voices of the Jedi',
  'Palpatine arena',
  'Adopted name',
]
