export const WORDS: string[] = [
  'Winter is coming',
  'Hodor',
  'The Hound',
  'Direwolf',
  'Dragon',
  'Iron Throne',
  'Jon Snow',
  'Daenerys Targaryen',
  'Cersei Lannister',
  'Tyrion Lannister',
  'Arya Stark',
  'Sansa Stark',
  'Bran Stark',
  'Night King',
  'White Walker',
  'Ned Stark',
  'Red Wedding',
  'The Wall',
  'King\'s Landing',
  'Dragonstone',
  'You know nothing',
  'Dracarys',
  'Valyrian steel',
  'Wildfire',
  'Ravens',
  'Three-eyed raven',
  'The Mountain',
  'The Viper',
  'Dothraki',
  'Beyond the Wall',
  'Shame',
  'A man has no name',
  'The Faith',
  'Lannister gold',
  'Stark honour',
  'Bend the knee',
  'Lord of Light',
  'Melisandre',
  'Littlefinger',
  'Varys',
  'Jorah',
  'Brienne',
  'Jaime',
  'The Imp',
  'Blackwater',
]
