export const WORDS: string[] = [
  'That\'s what she said',
  'Dunder Mifflin',
  'Michael Scott',
  'Dwight Schrute',
  'Jim Halpert',
  'Pam Beesly',
  'The Dundies',
  'Prison Mike',
  'Kevin\'s chili',
  'Pretzel Day',
  'Ryan started the fire',
  'Threat Level Midnight',
  'Assistant to the regional manager',
  'Identity theft',
  'Toby from HR',
  'Casual Friday',
  'Safety training',
  'CPR training',
  'Phyllis',
  'Stanley',
  'Andy Bernard',
  'Angela',
  'Oscar',
  'Kelly Kapoor',
  'Ryan Howard',
  'Creed',
  'Birthday party',
  'Conference room',
  'Yankee swap',
  'Parkour',
  'Fire drill',
  'Scott\'s Tots',
  'Goodbye Michael',
  'Bears beets Battlestar Galactica',
  'Recyclops',
  'Schrute Farms',
  'The annex',
  'Talking head',
  'Beach games',
  'Stress relief',
]
