export const WORDS: string[] = [
  'Vito Corleone',
  'Michael Corleone',
  'Sonny Corleone',
  'Fredo Corleone',
  'Tom Hagen',
  'Kay Adams',
  'Luca Brasi',
  'Sollozzo',
  'Captain McCluskey',
  'Virgil Sollozzo',
  'Jack Woltz',
  'Carlo Rizzi',
  'Long Island estate',
  'Sicily',
  'hospital',
  'horse head',
  'gun in restaurant bathroom',
  'orange',
  'wedding opening',
  'Bonasera',
  'I\'m gonna make him an offer he can\'t refuse',
  'Leave the gun, take the cannoli',
  'It\'s not personal, it\'s business',
  'A man who doesn\'t spend time with his family can never be a real man',
  'Don\'t ever take sides with anyone against the Family',
  'I believe in America',
  'Tollbooth hit',
  'Michael in exile',
  'Apollonia',
  'Sicilian thunderbolt',
  'The Turk',
  'Hospital corridor bluff',
  'Corleone compound',
  'Five Families',
  'Baptism murders',
  'Moe Greene',
  'Las Vegas move',
  'Connie\'s wedding',
  'Family business',
  'Michael closes the door',
]
