export const WORDS: string[] = [
  'Michael Corleone',
  'young Vito Corleone',
  'Fredo Corleone',
  'Hyman Roth',
  'Frank Pentangeli',
  'Senator Geary',
  'Connie Corleone',
  'Cuba',
  'Lake Tahoe',
  'Sicily flashbacks',
  'Congressional hearing',
  'I know it was you Fredo',
  'Keep your friends close, but your enemies closer',
  'This is the business we\'ve chosen',
  'My father taught me many things',
  'Fredo betrayal',
  'Senate hearing',
  'Cuba New Year\'s Eve',
  'Johnny Ola',
  'Havana rooftops',
  'Fanucci',
  'Little Italy feast',
  'Ellis Island',
  'Vito assassination attempt',
  'Lake Tahoe compound',
  'Communist revolution',
  'Pentangeli testimony',
  'Rosato brothers',
  'Michael\'s cold stare',
  'Hyman Roth birthday cake',
  'Mama Corleone funeral',
  'Window kiss of death',
  'Power and isolation',
  'Young Vito in Sicily',
  'Orange peels',
  'Roth in Havana',
  'Family betrayal',
  'Silent ending',
  'Fredo on the lake',
  'Michael alone',
]
