export const WORDS: string[] = [
  'Michael Corleone',
  'Vincent Corleone',
  'Mary Corleone',
  'Connie Corleone',
  'Archbishop Gilday',
  'Don Altobello',
  'Joey Zasa',
  'Vatican',
  'Atlantic City',
  'Sicily opera house',
  'Just when I thought I was out they pull me back in',
  'The higher I go the crookeder it becomes',
  'Vincent becomes the new Don',
  'Mary\'s death at the opera',
  'Papal finances',
  'Immobiliare',
  'Redemption attempt',
  'Order of St. Sebastian',
  'Helicopter attack',
  'Cavalleria Rusticana',
  'Michael\'s diabetic stroke',
  'Kay returns',
  'Corleone legitimacy',
  'Don Tommasino',
  'Zasa showdown',
  'Don Altobello\'s glasses',
  'Poisoned cannoli',
  'Vincent and Mary',
  'Sicilian vendetta',
  'Opera intercut killings',
  'Confession to Cardinal Lamberto',
  'The Vatican Bank',
  'New Pope',
  'Michael\'s scream',
  'Old age in Sicily',
  'Family curse',
  'The last Corleone',
  'Orange again',
  'Honor and guilt',
  'Final collapse',
]
