export const WORDS: string[] = [
  'wireframe',
  'mockup',
  'prototype',
  'figma',
  'user flow',
  'information architecture',
  'navigation',
  'hierarchy',
  'whitespace',
  'typography',
  'color palette',
  'contrast ratio',
  'accessibility',
  'WCAG',
  'component library',
  'design system',
  'atomic design',
  'tokens',
  'spacing',
  'grid',
  'breakpoint',
  'responsive',
  'mobile-first',
  'dark mode',
  'illustration',
  'iconography',
  'animation',
  'micro-interaction',
  'loading state',
  'empty state',
  'error state',
  'success state',
  'feedback',
  'affordance',
  'discoverability',
  'cognitive load',
  'mental model',
  'progressive disclosure',
  'onboarding',
  'tooltip',
  'modal',
  'drawer',
  'toast',
  'snackbar',
  'skeleton',
  'shimmer',
  'hero',
  'CTA',
  'above the fold',
  'scroll depth',
  'eye tracking',
]
