export const WORDS: string[] = [
  'performance review',
  'headcount',
  'talent pipeline',
  'onboarding',
  'offboarding',
  'culture add',
  'values alignment',
  'psychological safety',
  'feedback loop',
  'growth plan',
  'career ladder',
  'skip level',
  'PIP',
  'HRBP',
  'people ops',
  'engagement survey',
  'eNPS',
  'pulse check',
  'inclusion',
  'belonging',
  'compensation review',
  'leveling',
  'total rewards',
  'benefits',
  'parental leave',
  'hybrid',
  'async-first',
  'core hours',
  'team building',
  'offsites',
  'town hall',
  'culture deck',
  'handbook',
  'org design',
  'span of control',
  'succession planning',
  'attrition',
  'retention strategy',
  'work-life balance',
  'burnout',
  'wellbeing',
  'EAP',
  'diversity hire',
  'blind screening',
  'structured interview',
  'culture fit',
  'values interview',
  'reference check',
  'offer letter',
  'equity refresh',
]
