export const WORDS: string[] = [
  'strategic alignment',
  'headcount',
  'budget freeze',
  'OKRs',
  'KPIs',
  'town hall',
  'all-hands',
  'org restructure',
  'performance review',
  'top talent',
  'culture fit',
  'change management',
  'digital transformation',
  'cost center',
  'quarterly review',
  'board presentation',
  'market share',
  'risk management',
  'compliance',
  'ESG',
  'diversity quota',
  'hybrid policy',
  'return to office',
  'synergy',
  'stakeholder',
  'executive alignment',
  'vision statement',
  'north star',
  'transformation roadmap',
  'capacity planning',
  'resource allocation',
  'trade-off',
  'prioritization',
  'escalation',
  'bandwidth',
  'buy-in',
  'accountability',
  'cross-functional',
  'silo',
  'transparency',
  'psychological safety',
  'growth mindset',
  'stretch goal',
  'low-hanging fruit',
  'quick win',
  'deep dive',
  'parking lot',
  'take it offline',
  'circle back',
  'actionable insight',
  'data-driven',
  'impact',
]
