export const WORDS: string[] = [
  'discovery',
  'problem statement',
  'jobs to be done',
  'user research',
  'persona',
  'journey map',
  'pain point',
  'opportunity sizing',
  'PRD',
  'MRD',
  'feature request',
  'backlog grooming',
  'prioritization',
  'RICE score',
  'impact effort matrix',
  'north star metric',
  'OKR',
  'hypothesis',
  'A/B test',
  'experiment',
  'rollout',
  'feature flag',
  'dogfooding',
  'beta user',
  'customer interview',
  'NPS',
  'CSAT',
  'retention',
  'activation',
  'aha moment',
  'product-market fit',
  'CAC',
  'LTV',
  'churn',
  'funnel',
  'conversion rate',
  'cohort analysis',
  'retention curve',
  'DAU',
  'MAU',
  'stickiness',
  'engagement',
  'session length',
  'time to value',
  'onboarding flow',
  'empty state',
  'progressive disclosure',
  'design system',
  'accessibility',
  'mobile-first',
]
