export const WORDS: string[] = [
  'decision maker',
  'budget approved',
  'quarterly target',
  'discount request',
  'competitor mention',
  'POC',
  'pilot program',
  'contract review',
  'legal sign-off',
  'procurement',
  'use case demo',
  'pain point',
  'value proposition',
  'ROI',
  'next steps',
  'follow-up email',
  'objection handling',
  'pipeline review',
  'forecast',
  'close plan',
  'champion identified',
  'C-suite buy-in',
  'redline',
  'SLA negotiation',
  'renewal',
  'upsell',
  'expansion',
  'NPS score',
  'customer success',
  'churn risk',
  'cold call',
  'warm lead',
  'discovery',
  'qualification',
  'BANT',
  'mutual action plan',
  'executive sponsor',
  'proof of value',
  'business case',
  'total cost',
  'competitive pricing',
  'preferred vendor',
  'go-live date',
  'implementation',
  'onboarding plan',
  'success metrics',
  'QBR',
  'health score',
  'product roadmap ask',
  'compliance check',
  'security review',
  'reference call',
  'case study',
]
