export const WORDS: string[] = [
  'PR review',
  'merge conflict',
  'flaky test',
  'tech debt',
  'refactor',
  'breaking change',
  'hotfix',
  'rollback',
  'regression',
  'feature flag',
  'code review',
  'CI/CD',
  'pipeline failed',
  'green build',
  'deploy',
  'incident',
  'postmortem',
  'on-call',
  'SLA breach',
  'null pointer',
  'race condition',
  'memory leak',
  'query timeout',
  'cache miss',
  'rate limit',
  'dependency update',
  'security patch',
  'code freeze',
  'staging',
  'production',
  'monitoring alert',
  'latency spike',
  'load test',
  'documentation',
  'unit test',
  'integration test',
  'E2E test',
  'type error',
  'linter',
  'dead code',
  'rebase',
  'squash',
  'cherry-pick',
  'hotpath',
  'profiling',
  'containerize',
  'Kubernetes',
  'Docker',
  'serverless',
  'microservice',
  'message queue',
  'event-driven',
  'observability',
  'tracing',
  'logging',
]
