export const WORDS: string[] = [
  'Agnetha Fältskog',
  'Björn Ulvaeus',
  'Benny Andersson',
  'Anni-Frid Lyngstad',
  'Dancing Queen',
  'Waterloo',
  'Mamma Mia',
  'Fernando',
  'Voulez-Vous',
  'Gimme! Gimme! Gimme!',
  'The Winner Takes It All',
  'SOS',
  'Super Trouper',
  'Knowing Me Knowing You',
  'Eurovision 1974',
  'Swedish pop',
  'ABBA Gold',
  'Mamma Mia musical',
  'Mamma Mia movie',
  'ABBA Voyage hologram concert',
  'ABBA acronym',
  'Swedish accent',
  'disco era',
  'Voulez-Vous groove',
  'Fernando in a singalong',
  'Platform boots',
  'Piano pop sparkle',
  'Frida and Agnetha harmonies',
  'Gold lamé costumes',
  'Take a Chance on Me',
  'Chiquitita',
  'Honey Honey',
  'Dancing Queen piano intro',
  'Waterloo victory',
  'Pop perfection',
  'Disco revival',
  'The Winner Takes It All heartbreak',
  'Voyage avatars',
  'Scandinavian supergroup',
  'Glitter and melodies',
]
