export const WORDS: string[] = [
  'John Lennon',
  'Paul McCartney',
  'George Harrison',
  'Ringo Starr',
  'Pete Best',
  'Hey Jude',
  'Let It Be',
  'Come Together',
  'Yesterday',
  'Help!',
  'A Hard Day\'s Night',
  'Twist and Shout',
  'Something',
  'Blackbird',
  'Eleanor Rigby',
  'Sgt. Pepper\'s Lonely Hearts Club Band',
  'Abbey Road',
  'Revolver',
  'White Album',
  'Ed Sullivan Show',
  'Rooftop concert',
  'breakup 1970',
  'Beatlemania',
  'Liverpool',
  'The Cavern Club',
  'Mop-top haircuts',
  'Yellow Submarine',
  'Penny Lane',
  'Strawberry Fields Forever',
  'All You Need Is Love',
  'George on sitar',
  'Paul\'s bass',
  'Ringo\'s backbeat',
  'Lennon glasses',
  'Crosswalk album cover',
  'Apple Corps',
  'British Invasion',
  'She loves you yeah yeah yeah',
  'Studio experimentation',
  'Fab Four',
]
