export const WORDS: string[] = [
  'Jimmy Page',
  'Robert Plant',
  'John Bonham',
  'John Paul Jones',
  'Stairway to Heaven',
  'Whole Lotta Love',
  'Kashmir',
  'Black Dog',
  'Rock and Roll',
  'Immigrant Song',
  'Communication Breakdown',
  'Led Zeppelin IV',
  'Physical Graffiti',
  'Houses of the Holy',
  'legendary status',
  'guitar solos',
  'Plant\'s wail',
  'Bonham\'s drums',
  'Hammer of the Gods',
  'Atlantic Records',
  'Been a long time',
  'Misty Mountain Hop',
  'When the Levee Breaks',
  'Dazed and Confused',
  'Ramble On',
  'Going to California',
  'The Song Remains the Same',
  'No Quarter',
  'Whole Lotta riffs',
  'Double-neck guitar',
  'Stairway banned in stores',
  'Viking imagery',
  'Blues rock thunder',
  'Bonzo',
  'Page violin bow',
  'Zeppelin airship',
  'Physical Graffiti cover',
  'Epic live jams',
  '1970s rock gods',
  'Drum break obsession',
]
