export const WORDS: string[] = [
  'James Hetfield',
  'Lars Ulrich',
  'Kirk Hammett',
  'Robert Trujillo',
  'Cliff Burton',
  'Enter Sandman',
  'Master of Puppets',
  'One',
  'Nothing Else Matters',
  'Fade to Black',
  'Seek and Destroy',
  'Battery',
  'Wherever I May Roam',
  'Black Album',
  'Ride the Lightning',
  '...And Justice for All',
  'thrash metal',
  'heavy riffs',
  'Lars drumming',
  'stadium tours',
  'Download Festival',
  'Whiplash',
  'For Whom the Bell Tolls',
  'Creeping Death',
  'Sad But True',
  'The Unforgiven',
  'Mosh pit',
  'Downpicking machine',
  'Master! Master!',
  'Cliff Burton bass intro',
  'Snake pit',
  'Kill "Em All',
  'Live in Moscow',
  'S&M orchestra',
  'Blackened',
  'Metal horns',
  'Hetfield yeah!',
  'Kirk wah pedal',
  'San Francisco metal',
  'Arena pyro',
]
