export const WORDS: string[] = [
  'Michael Jackson',
  'Thriller',
  'Billie Jean',
  'Beat It',
  'Smooth Criminal',
  'Bad',
  'Black or White',
  'Man in the Mirror',
  'Don\'t Stop \'Til You Get Enough',
  'Rock with You',
  'Heal the World',
  'Thriller album',
  'Bad album',
  'Dangerous album',
  'Off the Wall',
  'Moonwalk',
  'Neverland',
  'Jackson 5',
  'Pepsi commercial',
  'MTV',
  'single glove',
  'fedora',
  'the lean move',
  'hee-hee',
  'HIStory tour',
  'Quincy Jones',
  'Red leather jacket',
  'Beat It guitar solo',
  'Billie Jean bassline',
  'Smooth Criminal hat tilt',
  'Motown 25',
  'King of Pop',
  'Super Bowl halftime',
  'Remember the Time',
  'Dirty Diana',
  'Man in the Mirror choir',
  'Black fedora silhouette',
  'Dangerous choreography',
  'Global superstar',
  'Legendary dance moves',
]
