export const WORDS: string[] = [
  'Kurt Cobain',
  'Dave Grohl',
  'Krist Novoselic',
  'Smells Like Teen Spirit',
  'Come as You Are',
  'Lithium',
  'Heart-Shaped Box',
  'About a Girl',
  'All Apologies',
  'Rape Me',
  'In Bloom',
  'Polly',
  'Nevermind',
  'In Utero',
  'Bleach',
  'MTV Unplugged in New York',
  'grunge',
  'Seattle',
  'flannel shirts',
  'the voice of a generation',
  'Kurt\'s death 1994',
  'Nevermind baby album cover',
  'Loud-quiet-loud',
  'Teen Spirit riff',
  'Cobain cardigan',
  'Unplugged candles',
  'Breed',
  'Drain You',
  'Lithium scream',
  'Punk energy',
  'DIY attitude',
  'Come As You Are watery guitar',
  'Krist\'s bass swing',
  'Dave before Foo Fighters',
  'Seattle scene',
  'Serve the Servants',
  'Sliver',
  'Rough edges',
  'Anti-rockstar vibe',
  'Generation X angst',
]
