export const WORDS: string[] = [
  'Freddie Mercury',
  'Brian May',
  'Roger Taylor',
  'John Deacon',
  'Bohemian Rhapsody',
  'We Will Rock You',
  'We Are the Champions',
  'Don\'t Stop Me Now',
  'Somebody to Love',
  'Under Pressure',
  'Radio Ga Ga',
  'I Want to Break Free',
  'Killer Queen',
  'Another One Bites the Dust',
  'A Night at the Opera',
  'Jazz',
  'The Game',
  'Live Aid 1985',
  'Freddie\'s death 1991',
  'Wembley crowd',
  'Operatic harmonies',
  'Stomp-stomp-clap',
  'Brian May guitar solo',
  'Red Special',
  'Roger\'s falsetto',
  'Deacon bassline',
  'Champions anthem',
  'Is this the real life?',
  'Galileo',
  'Scaramouche',
  'Bicycle Race',
  'Fat Bottomed Girls',
  'The Show Must Go On',
  'Flash Gordon soundtrack',
  'Queen crest',
  'Glam rock flair',
  'Arena singalong',
  'Mercury yellow jacket',
  'Tribute concert',
  'Legendary frontman',
]
