export const WORDS: string[] = [
  'Mick Jagger',
  'Keith Richards',
  'Charlie Watts',
  'Ronnie Wood',
  'Brian Jones',
  'Paint It Black',
  'Sympathy for the Devil',
  '(I Can\'t Get No) Satisfaction',
  'Gimme Shelter',
  'Start Me Up',
  'Jumpin\' Jack Flash',
  'Brown Sugar',
  'Wild Horses',
  'Miss You',
  'Angie',
  'Exile on Main St.',
  'Sticky Fingers',
  'Let It Bleed',
  'iconic lips logo',
  'Altamont',
  'Steel Wheels tour',
  'Mick\'s moves',
  'Keith riff',
  'Tumbling Dice',
  'You Can\'t Always Get What You Want',
  'Street Fighting Man',
  'Midnight Rambler',
  'Paint it black sitar',
  'Bluesy swagger',
  'World\'s greatest rock and roll band',
  'Open G tuning',
  'Tongue logo',
  'Charlie\'s steady groove',
  'Brown sugar controversy',
  'Satisfaction fuzz riff',
  'London rock royalty',
  'Decades on tour',
  'Ronnie on guitar',
  'Jagger strut',
  'Classic rock survivors',
]
