export const DEFAULT_WORDS: string[] = [
  "synergy", "alignment", "pivot", "agile", "sprint", 
  "blocker", "bandwidth", "offline", "circle back", "deep dive",
  "touch base", "wheelhouse", "low-hanging fruit", "move the needle", "paradigm shift",
  "cadence", "ROI", "KPIs", "metrics", "deliverables",
  "action items", "stakeholders", "buy-in", "leverage", "scalable",
  "robust", "disruptive", "ecosystem", "drill down", "optics",
  "pushback", "value add", "best practice", "bottom line", "pain point",
  "roadmap", "runway", "traction", "seamless", "integration",
  "onboarding", "churn", "friction", "granularity", "holistic",
  "ideation", "iteration", "bottleneck", "capacity", "velocity",
  "scrum", "kanban", "backlog", "standup", "retro",
  "deploy", "pipeline", "stack", "cloud", "on-prem",
  "API", "microservices", "infrastructure", "latency", "throughput",
  "MVP", "POC", "use case", "user story", "epic",
  "wireframe", "mockup", "UX", "UI", "journey",
  "conversion", "funnel", "monetize", "freemium", "B2B",
  "B2C", "SaaS", "open source", "compliance", "GDPR",
  "security", "feature", "enhancement", "QA", "staging",
  "production", "refactor", "tech debt", "pull request", "repo",
  "CI/CD", "automation", "DevOps", "machine learning", "AI",
  "algorithm", "data-driven", "analytics", "dashboard", "insights",
  "big data", "cloud-native", "serverless", "container", "architecture",
  "ping", "sync", "on the same page", "reach out", "loop in",
  "actionable", "game changer", "value proposition", "core competency", "sweat equity",
  "burn rate", "thought leadership", "mindshare", "growth hacking", "win-win",
  "bleeding edge", "cutting edge", "state of the art", "best in class", "whiteboard",
  "brainstorm", "kickoff", "post-mortem", "debrief", "all-hands",
  "town hall", "1-on-1", "facetime", "hard stop", "parking lot",
  "soft launch", "hard launch", "beta", "alpha", "go-to-market",
  "TAM", "LTV", "CAC", "ARR", "MRR",
  "retention", "engagement", "on the radar", "out of the box", "boil the ocean",
  "move the goalposts", "ducks in a row", "herding cats", "drink the kool-aid", "dogfooding",
  "helicopter view", "10,000-foot view", "in the weeds", "table stakes", "north star",
  "flywheel", "blue sky", "unpack", "double click", "async",
  "scope creep", "timebox", "cross-functional", "champion", "upskill",
  "reskill", "out of pocket", "per my last email", "take a step back", "full transparency",
  "single source of truth", "ideate", "orthogonal", "swimlane", "silos",
  "cross-pollinate", "greenfield", "brownfield", "quick win", "heavy lifting",
  "punt", "right-size", "scale back", "ramp up", "sunset",
  "deprecate", "end of life", "ping me", "read out", "knowledge transfer"
];

