export const WORDS: string[] = [
  'Owen Grady',
  'Claire Dearing',
  'Maisie Lockwood',
  'Alan Grant',
  'Ellie Sattler',
  'Ian Malcolm',
  'Lewis Dodgson',
  'Rainn Delacourt',
  'Barry',
  'Dr. Wu',
  'Gigantosaurus',
  'Pyroraptor',
  'Therizinosaurus',
  'Dreadnoughtus',
  'Quetzalcoatlus',
  'Atrociraptors',
  'Biosyn valley',
  'Malta',
  'dinosaurs in the wild',
  'Dinosaurs and humans living together',
  'Biosyn sanctuary',
  'Ellie and Alan reunion',
  'Locust plague engineered',
  'We created them, we have a responsibility',
  'Malcolm was right all along',
  'Original cast returns',
  'Amber mines',
  'Hyperloop chase',
  'Frozen lake Pyroraptor',
  'Blind Therizinosaurus',
  'Pilot in Malta',
  'Black market dinosaur fight',
  'Beta the baby raptor',
  'Maisie\'s origin',
  'Dodgson with the Barbasol can',
  'Giga versus Rexy',
  'Campfire with the old crew',
  'Bioengineered locusts',
  'Sanctuary valley fire',
  'New coexistence status quo',
]
