export const WORDS: string[] = [
  'Owen Grady',
  'Claire Dearing',
  'Maisie Lockwood',
  'Benjamin Lockwood',
  'Eli Mills',
  'Dr. Wu',
  'Zia Rodriguez',
  'Franklin Webb',
  'Ken Wheatley',
  'Indoraptor',
  'Blue',
  'Carnotaurus',
  'Baryonyx',
  'Sinoceratops',
  'Isla Nublar volcano',
  'Lockwood estate',
  'underground auction',
  'She\'s not a thing, she\'s a child',
  'Indoraptor auction',
  'She opened the cages',
  'Maisie is a clone',
  'The island is gone',
  'Blue is alive',
  'They\'re going to sell them',
  'Volcanic ash',
  'Stygimoloch breakout',
  'Blood transfusion',
  'Submarine transport',
  'Wheatley collecting teeth',
  'Indoraptor on the roof',
  'Laser target system',
  'Mills\' mansion lab',
  'Brachiosaurus on the dock',
  'Mansion horror vibe',
  'Lockwood secret',
  'Auction paddocks',
  'Escaping lava',
  'Blue and Owen reunion',
  'Cryogenic elevator',
  'Dinosaurs released into the wild',
]
