export const WORDS: string[] = [
  'Dr. Alan Grant',
  'Paul Kirby',
  'Amanda Kirby',
  'Billy Brennan',
  'Eric Kirby',
  'Udesky',
  'Cooper',
  'Spinosaurus',
  'Pteranodons',
  'Velociraptors',
  'Baryonyx',
  'Isla Sorna',
  'Pteranodon Aviary',
  'river rescue',
  'Grant!',
  'The raptors are using the resonating chamber to communicate',
  'Spinosaurus vs T-Rex',
  'Pteranodon cage',
  'Raptor eggs',
  'Dinosaur urine',
  'Eric survived alone',
  'Navy rescue',
  'Kirby Paint and Tile Plus',
  'Satellite phone',
  'Billy steals the eggs',
  'Resonating chamber',
  'Paraglider opening',
  'Boat on the river',
  'Embryonics lab',
  'Bird cage bridge',
  'Raptor negotiation',
  'Amanda screaming',
  'Alan\'s nightmare raptor',
  'Marine arrival',
  'Lucky pack',
  'Survival kit',
  'Spinosaurus ringtone',
  'Udesky\'s end',
  'Ben Hildebrand',
  'Island bait-and-switch',
]
