export const WORDS: string[] = [
  'Owen Grady',
  'Claire Dearing',
  'Zach Mitchell',
  'Gray Mitchell',
  'Simon Masrani',
  'Vic Hoskins',
  'Barry',
  'Indominus Rex',
  'Blue',
  'trained raptors',
  'Mosasaurus',
  'Jurassic World park',
  'Hammond Creation Lab',
  'Innovation Center',
  'Mosasaurus tank',
  'You just went and made a new dinosaur',
  'Raptors have a new alpha',
  'Mosasaurus feeding show',
  'Pterodactyls attack the park',
  'She\'s communicating',
  'Asset out of containment',
  'It\'s a highly intelligent piece of equipment',
  'Clever girl',
  'Gyrosphere',
  'Main street panic',
  'Claire in heels',
  'Indominus camouflage',
  'Thermal signature trick',
  'Owen\'s raptor bond',
  'Control room lockdown',
  'Genetic hybrid',
  'Apatosaurus goodbye',
  'Masrani helicopter crash',
  'Pteranodon swarm',
  'Rexy returns',
  'Blue versus Indominus',
  'Water park finale',
  'Hoskins and Delta',
  'Kids in the old visitor center',
  'Theme park gone wrong',
]
