export const WORDS: string[] = [
  'Dr. Alan Grant',
  'Dr. Ellie Sattler',
  'Dr. Ian Malcolm',
  'John Hammond',
  'Dennis Nedry',
  'Tim Murphy',
  'Lex Murphy',
  'Ray Arnold',
  'Robert Muldoon',
  'T-Rex',
  'Velociraptors',
  'Dilophosaurus',
  'Brachiosaurus',
  'Triceratops',
  'Welcome to Jurassic Park',
  'Life finds a way',
  'Hold onto your butts',
  'Clever girl',
  'Spared no expense',
  'Objects in mirror are closer than they appear',
  'Shoot her!',
  'Mr. Hammond I think we\'re back in business',
  'They\'re moving in packs',
  'Ah ah ah, you didn\'t say the magic word',
  'Amber mosquito',
  'Electric fence',
  'Tour car goggles',
  'Kitchen raptor scene',
  'Goat on the chain',
  'Shaving cream can',
  'Chaos theory',
  'DNA frog gap',
  'Raptor pen',
  'T-Rex paddock',
  'Jeep chase',
  'Spinning DNA cartoon',
  'Mr. DNA',
  'Control room reset',
  'Helicopter landing',
  'Welcome banner',
]
