export const WORDS: string[] = [
  'Ian Malcolm',
  'Sarah Harding',
  'Nick Van Owen',
  'Peter Ludlow',
  'Roland Tembo',
  'Kelly Malcolm',
  'Eddie Carr',
  'Stegosaurus',
  'Compies',
  'Pachycephalosaurus',
  'T-Rex in San Diego',
  'Site B',
  'Isla Sorna',
  'InGen camp',
  'San Diego',
  'Ooh, aah, that\'s how it always starts, then later there\'s running and screaming',
  'Don\'t go into the long grass',
  'Mommy\'s very angry',
  'Two T-Rexes',
  'Baby Rex',
  'Hunters and gatherers',
  'High hide trailer',
  'Broken glass cliff',
  'Gymnastics kick',
  'Roland wants the buck',
  'Eddie cut in half',
  'Compy attack',
  'Engineer on the ship',
  'Ludlow\'s greed',
  'Stego photography',
  'Campsite chaos',
  'Mercedes SUV',
  'Boardroom on Hammond\'s island',
  'San Diego harbor',
  'Rex through downtown',
  'Tembo drinking whisky',
  'Gathering team',
  'Hunter cages',
  'Pachy headbutt',
  'Chaos returns',
]
